name: Github Workflow

on:
  push:
    branches:
      - main

jobs:
  first_interaction:
    name: First interaction
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v2
      - name: First Interaction
        uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for taking the time to post this issue. We appreciate your contribution! Please make sure you've searched for duplicates and describe your issue in detail. If you have any questions, feel free to ask."
